-- ─── Seed engine_games from the curated games.json ──────────────────────────
-- Auto-generated from content/solitaire/games.json (41 curated master
-- games). Re-runnable: on conflict it refreshes the stored copy. Curated rows
-- are inserted as the admin role (RLS bypassed) with source = 'curated'.
-- Regenerate with: node scripts/gen-seed.js (logic mirrored in 004 history).

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('spassky-karpov-1988', 'Karpov''s Caro-Kann', 'Caro-Kann Defense', 'B17', 'Boris V Spassky', 'Anatoly Karpov', 'World Cup', 1988, '0-1', 3, null, 7, '["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Ng5","Ndf6","Bc4","Nd5","N1f3","g6","O-O","Bg7","Re1","h6","Ne4","Bg4","a4","Ngf6","Nxf6+","Bxf6","Ra3","Kf8","h3","Bxf3","Rxf3","Kg7","c3","Qd7","Qd3","Rad8","Re4","Qc8","b4","Rd6","Rg3","Re6","Reg4","Re1+","Kh2","Rxc1"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('smyslov-botvinnik-1958', 'Smyslov vs Botvinnik, WC', 'Caro-Kann Defense', 'B11', 'Vassily Smyslov', 'Mikhail Botvinnik', 'World Championship 22th', 1958, '1-0', 4, null, 8, '["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","Nf6","d3","e6","a3","Be7","g4","Nfd7","d4","Nf8","Be3","Ng6","Qg3","Bh4","Qh2","Nd7","O-O-O","Qb8","f4","dxe4","Nxe4","Nf6","Nxf6+","Bxf6","Qf2","Bh4","Qf3","Ne7","Bd3","g6","f5","exf5","Bf4","Qd8","gxf5","Qd5","Qg4","Bf6","Rhe1","h5","Qg3","h4","Qg4","gxf5","Bxf5","Kf8","Be4","Qa2","c3","Rd8","Rf1","Nd5","Bd2","Rd6","Qc8+","Ke7","Qxb7+","Rd7","Rde1","Qa1+","Bb1+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('evergreen-1852', 'The Evergreen Game', 'Evans Gambit', 'C52', 'Adolf Anderssen', 'Jean Dufresne', 'Berlin ''Evergreen''', 1852, '1-0', 2, null, 10, '["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","d3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5","Qxb5","Rb8","Qa4","Bb6","Nbd2","Bb7","Ne4","Qf5","Bxd3","Qh5","Nf6+","gxf6","exf6","Rg8","Rad1","Qxf3","Rxe7+","Nxe7","Qxd7+","Kxd7","Bf5+","Ke8","Bd7+","Kf8","Bxe7#"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('bondarevsky-botvinnik-1941', 'Botvinnik''s French', 'French Defense', 'C02', 'Igor Bondarevsky', 'Mikhail Botvinnik', 'Leningrad/Moscow', 1941, '0-1', 4, null, 11, '["e4","e6","d4","d5","e5","c5","Nf3","Nc6","Bd3","cxd4","O-O","Bc5","a3","Nge7","Nbd2","Ng6","Nb3","Bb6","Re1","Bd7","g3","f6","Bxg6+","hxg6","Qd3","Kf7","h4","Qg8","Bd2","Qh7","Bb4","g5","Qxh7","Rxh7","exf6","gxf6","hxg5","e5","gxf6","Kxf6","Bd6","Re8","Nh4","Rg8","Kh2","Bf5","Re2","d3","Rd2","dxc2","f4","Be3","Bxe5+","Nxe5","fxe5+","Ke7","Rf1","c1=Q"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('tal-botvinnik-1960', 'Tal vs Botvinnik, WC 1960', 'French Defense', 'C18', 'Mihail Tal', 'Mikhail Botvinnik', 'World Championship 23th', 1960, '1-0', 4, null, 8, '["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Qc7","Qg4","f5","Qg3","Ne7","Qxg7","Rg8","Qxh7","cxd4","Kd1","Bd7","Qh5+","Ng6","Ne2","d3","cxd3","Ba4+","Ke1","Qxe5","Bg5","Nc6","d4","Qc7","h4","e5","Rh3","Qf7","dxe5","Ncxe5","Re3","Kd7","Rb1","b6","Nf4","Rae8","Rb4","Bc6","Qd1","Nxf4","Rxf4","Ng6","Rd4","Rxe3+","fxe3","Kc7","c4","dxc4","Bxc4","Qg7","Bxg8","Qxg8","h5"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('game-of-the-century-1956', 'The Game of the Century', 'Grünfeld Defense', 'D97', 'Donald Byrne', 'Robert James Fischer', 'New York Rosenwald', 1956, '0-1', 4, null, 9, '["Nf3","Nf6","c4","g6","Nc3","Bg7","d4","O-O","Bf4","d5","Qb3","dxc4","Qxc4","c6","e4","Nbd7","Rd1","Nb6","Qc5","Bg4","Bg5","Na4","Qa3","Nxc3","bxc3","Nxe4","Bxe7","Qb6","Bc4","Nxc3","Bc5","Rfe8+","Kf1","Be6","Bxb6","Bxc4+","Kg1","Ne2+","Kf1","Nxd4+","Kg1","Ne2+","Kf1","Nc3+","Kg1","axb6","Qb4","Ra4","Qxb6","Nxd1","h3","Rxa2","Kh2","Nxf2","Re1","Rxe1","Qd8+","Bf8","Nxe1","Bd5","Nf3","Ne4","Qb8","b5","h4","h5","Ne5","Kg7","Kg1","Bc5+","Kf1","Ng3+","Ke1","Bb4+","Kd1","Bb3+","Kc1","Ne2+","Kb1","Nc3+","Kc1","Rc2#"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('immortal-1851', 'The Immortal Game', 'King''s Gambit', 'C33', 'Adolf Anderssen', 'Lionel Kieseritzky', 'London ''Immortal game''', 1851, '1-0', 3, null, 4, '["e4","e5","f4","exf4","Bc4","Qh4+","Kf1","b5","Bxb5","Nf6","Nf3","Qh6","d3","Nh5","Nh4","Qg5","Nf5","c6","g4","Nf6","Rg1","cxb5","h4","Qg6","h5","Qg5","Qf3","Ng8","Bxf4","Qf6","Nc3","Bc5","Nd5","Qxb2","Bd6","Bxg1","e5","Qxa1+","Ke2","Na6","Nxg7+","Kd8","Qf6+","Nxf6","Be7#"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('opera-game-1858', 'The Opera Game', 'Philidor Defense', 'C41', 'Paul Morphy', 'Duke of Brunswick & Count Isouard', 'Paris it', 1858, '1-0', 1, null, 3, '["e4","e5","Nf3","d6","d4","Bg4","dxe5","Bxf3","Qxf3","dxe5","Bc4","Nf6","Qb3","Qe7","Nc3","c6","Bg5","b5","Nxb5","cxb5","Bxb5+","Nbd7","O-O-O","Rd8","Rxd7","Rxd7","Rd1","Qe6","Bxd7+","Nxd7","Qb8+","Nxb8","Rd8#"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('kasparov-topalov-1999', 'Kasparov''s Immortal', 'Pirc Defense', 'B07', 'Gary Kasparov', 'Veselin Topalov', 'Hoogovens', 1999, '1-0', 5, null, 8, '["e4","d6","d4","Nf6","Nc3","g6","Be3","Bg7","Qd2","c6","f3","b5","Nge2","Nbd7","Bh6","Bxh6","Qxh6","Bb7","a3","e5","O-O-O","Qe7","Kb1","a6","Nc1","O-O-O","Nb3","exd4","Rxd4","c5","Rd1","Nb6","g3","Kb8","Na5","Ba8","Bh3","d5","Qf4+","Ka7","Rhe1","d4","Nd5","Nbxd5","exd5","Qd6","Rxd4","cxd4","Re7+","Kb6","Qxd4+","Kxa5","b4+","Ka4","Qc3","Qxd5","Ra7","Bb7","Rxb7","Qc4","Qxf6","Kxa3","Qxa6+","Kxb4","c3+","Kxc3","Qa1+","Kd2","Qb2+","Kd1","Bf1","Rd2","Rd7","Rxd7","Bxc4","bxc4","Qxh8","Rd3","Qa8","c3","Qa4+","Ke1","f4","f5","Kc1","Rd2","Qa7"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('fischer-spassky-1972-g6', 'Fischer vs Spassky, Game 6', 'Queen''s Gambit', 'D59', 'Robert James Fischer', 'Boris V Spassky', 'World Championship 28th', 1972, '1-0', 3, null, 10, '["c4","e6","Nf3","d5","d4","Nf6","Nc3","Be7","Bg5","O-O","e3","h6","Bh4","b6","cxd5","Nxd5","Bxe7","Qxe7","Nxd5","exd5","Rc1","Be6","Qa4","c5","Qa3","Rc8","Bb5","a6","dxc5","bxc5","O-O","Ra7","Be2","Nd7","Nd4","Qf8","Nxe6","fxe6","e4","d4","f4","Qe7","e5","Rb8","Bc4","Kh8","Qh3","Nf8","b3","a5","f5","exf5","Rxf5","Nh7","Rcf1","Qd8","Qg3","Re7","h4","Rbb7","e6","Rbc7","Qe5","Qe8","a4","Qd8","R1f2","Qe8","R2f3","Qd8","Bd3","Qe8","Qe4","Nf6","Rxf6","gxf6","Rxf6","Kg8","Bc4","Kh8","Qf4"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('capablanca-alekhine-1913', 'Capablanca vs Alekhine', 'Queen''s Gambit', 'D30', 'Jose Raul Capablanca', 'Alexander Alekhine', 'St Petersburg exhibition', 1913, '1-0', 4, null, 9, '["d4","d5","c4","c6","e3","Nf6","Nf3","e6","Nbd2","Nbd7","Bd3","Be7","O-O","O-O","Qc2","dxc4","Nxc4","c5","Nce5","cxd4","exd4","Nb6","Ng5","g6","Ngf3","Kg7","Bg5","Nbd5","Rac1","Bd7","Qd2","Ng8","Bxe7","Qxe7","Be4","Bb5","Rfe1","Qd6","Bxd5","exd5","Qa5","a6","Qc7","Qxc7","Rxc7","h6","Rxb7","Rac8","b3","Rc2","a4","Be2","Nh4","h5","Nhxg6","Re8","Rxf7+","Kh6","f4","a5","Nh4","Rxe5","fxe5","Kg5","g3","Kg4","Rg7+","Kh3","Ng2"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-gelfand-2011', 'Carlsen vs Gelfand, Tal Memorial', 'Queen''s Gambit', 'D12', 'M. Carlsen', 'B. Gelfand', '6th Tal Memorial', 2011, '1-0', 4, null, 8, '["d4","d5","c4","c6","Nf3","Nf6","e3","Bf5","Nc3","e6","Nh4","Bg6","Nxg6","hxg6","Bd3","Nbd7","O-O","Bd6","h3","dxc4","Bxc4","Nb6","Bb3","e5","Qc2","Qe7","Bd2","O-O-O","d5","e4","dxc6","Qe5","f4","exf3","Rxf3","Ng4","cxb7+","Kb8","hxg4","Rh1+","Kf2","Rxa1","Ne2","Bc5","Bc3","Qe7","g5","Rdd1","Ng3","Bd6","Qe2","Rg1","Qd3","Bc7","Ne4","Raf1+","Ke2","Rxf3","gxf3","f5","gxf6","gxf6","Bxf6","Qh7","Qb5","Rg2+","Kd3","Qd7+","Qxd7","Nxd7","Bd5","Be5","f4","Bc7","Bc6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('fischer-bernstein-1959', 'Fischer''s Marshall Defense', 'Ruy Lopez', 'C89', 'Robert James Fischer', 'Sidney Norman Bernstein', 'USA-ch', 1959, '1-0', 3, null, 10, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","O-O","c3","d5","exd5","e4","dxc6","exf3","Qxf3","Bg4","Qg3","Bd6","Qh4","Re8","f3","Bf5","d4","Bxh2+","Kxh2","Ng4+","Kg3","Qxh4+","Kxh4","Rxe1","fxg4","Rxc1","gxf5","Rd8","a4","b4","d5","Rb8","d6","cxd6","Bc4","Rc8","Bxa6","Rxc6","Bb5","Rb6","c4","d5","a5","g5+","Kxg5","h6+","Kg4","Rb8","a6","dxc4","a7","Ra8","Bc6","h5+","Kg5","Rxb1","Rxb1","Rxa7","Rc1","Ra2","Rxc4","Rxb2","f6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('karpov-unzicker-1975', 'Karpov vs Unzicker, Milan', 'Ruy Lopez', 'C97', 'Anatoly Karpov', 'Wolfgang Unzicker', 'Milan', 1975, '1-0', 4, null, 15, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","d6","c3","O-O","h3","Na5","Bc2","c5","d4","Qc7","Nbd2","Bd7","Nf1","Rfe8","d5","Nb7","N3h2","g6","Ng3","c4","f4","exf4","Bxf4","Bf8","Bg5","Be7","Qd2","Bc8","Rf1","Nd7","Ng4"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-shirov-2005', 'Carlsen vs Shirov', 'Ruy Lopez', 'C95', 'M. Carlsen', 'A. Shirov', 'Smartfish Masters', 2005, '1-0', 4, null, 14, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","O-O","c3","d6","h3","Nb8","d4","Nbd7","Nbd2","Bb7","Bc2","Re8","Nf1","Bf8","Ng3","g6","b3","c6","Bg5","Bg7","Qd2","Qc7","a4","d5","dxe5","Nxe5","Nxe5","Qxe5","Bf4","Qe6","e5","Nd7","Bh6","Bh8","f4","Qe7","Re3","Nf8","Rf1","c5","f5","d4","cxd4","cxd4","fxg6","hxg6","Nf5","gxf5","Rg3+","Ng6","Bxf5","Qxe5","Rg4","Bg7","Bxg6","fxg6","Rxg6","Re7","Rf4","Be4","Rg5","Qe6","Bxg7"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-anand-2014-g11', 'Carlsen vs Anand, Game 11', 'Ruy Lopez', 'C67', 'M. Carlsen', 'V. Anand', 'WCh 2014', 2014, '1-0', 5, null, 11, '["e4","e5","Nf3","Nc6","Bb5","Nf6","O-O","Nxe4","d4","Nd6","Bxc6","dxc6","dxe5","Nf5","Qxd8+","Kxd8","h3","Bd7","Nc3","h6","b3","Kc8","Bb2","c5","Rad1","b6","Rfe1","Be6","Nd5","g5","c4","Kb7","Kh2","a5","a4","Ne7","g4","Ng6","Kg3","Be7","Nd2","Rhd8","Ne4","Bf8","Nef6","b5","Bc3","bxa4","bxa4","Kc6","Kf3","Rdb8","Ke4","Rb4","Bxb4","cxb4","Nh5","Kb7","f4","gxf4","Nhxf4","Nxf4","Nxf4","Bxc4","Rd7","Ra6","Nd5","Rc6","Rxf7","Bc5","Rxc7+","Rxc7","Nxc7","Kc6","Nb5","Bxb5","axb5+","Kxb5","e6","b3","Kd3","Be7","h4","a4","g5","hxg5","hxg5","a3","Kc3"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('tal-tringov-1958', 'Tal''s Munich Brilliancy', 'Sicilian Defense', 'B96', 'Mihail Tal', 'Georgi P Tringov', 'Munich olm fin-A', 1958, '1-0', 4, null, 9, '["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bg5","e6","f4","h6","Bh4","Qb6","Nb3","Qe3+","Be2","Qxf4","Bg3","Qe3","Bxd6","Nc6","Rf1","Nxe4","Nxe4","Qxe4","Bxf8","Rxf8","Kf2","Bd7","Qxd7+","Kxd7","Nc5+","Ke7","Nxe4","f5","Nc5"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('tal-larsen-1958', 'Tal vs Larsen, Portoroz', 'Sicilian Defense', 'B94', 'Mihail Tal', 'Bent Larsen', 'Portoroz Interzonal', 1958, '1-0', 4, null, 10, '["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bg5","Nbd7","Bc4","Qa5","Qd2","e6","O-O","h6","Bh4","Be7","Rad1","Ne5","Bb3","g5","Bg3","Bd7","f4","gxf4","Bxf4","Nh5","Bxe5","Qxe5","Kh1","Nf6","Nf3","Qh5","e5","dxe5","Ne4","O-O-O","Ng3","Qg4","Nxe5","Qh4","Qc3+","Kb8","Nxd7+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-anand-2014-g2', 'Carlsen vs Anand, Game 2', 'Sicilian Defense', 'B41', 'M. Carlsen', 'V. Anand', 'WCh 2014', 2014, '1-0', 4, null, 11, '["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6","c4","Nf6","Nc3","Bb4","Qd3","Nc6","Nxc6","dxc6","Qxd8+","Kxd8","e5","Nd7","Bf4","Bxc3+","bxc3","Kc7","h4","b6","h5","h6","O-O-O","Bb7","Rd3","c5","Rg3","Rag8","Bd3","Nf8","Be3","g6","hxg6","Nxg6","Rh5","Bc6","Bc2","Kb7","Rg4","a5","Bd1","Rd8","Bc2","Rdg8","Kd2","a4","Ke2","a3","f3","Rd8","Ke1","Rd7","Bc1","Ra8","Ke2","Ba4","Be4+","Bc6","Bxg6","fxg6","Rxg6","Ba4","Rxe6","Rd1","Bxa3","Ra1","Ke3","Bc2","Re7+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('kasparov-polugaevsky-1979', 'Kasparov vs Polugaevsky', 'Sicilian Defense', 'B81', 'Gary Kasparov', 'Lev Polugaevsky', 'URS Spartakiad', 1979, '1-0', 5, null, 8, '["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6","Be3","a6","g4","Nc6","g5","Nd7","Rg1","Be7","h4","O-O","h5","Nde5","Nxc6","Nxc6","f4","b5","Qf3","Bb7","Bd3","Nb4","f5","exf5","Qxf5","Nxd3+","cxd3","Qc8","h6","Re8","hxg7","Qxf5","exf5","Bxg5","Rxg5","Rxe3+","Kd2","Rf3","Ne4","Bxe4","dxe4","Re8","Rc1","d5","e5","h6","Rh5","Rxe5","f6","Rf2+","Kd3","Rf3+","Kd4","Re4+","Kxd5","Re8","Rxh6","Rf5+","Kd4","Rf4+","Kc5","Re5+","Kb6","Re6+","Rc6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-caruana-2018-tiebreak', 'Carlsen vs Caruana, Tiebreak', 'Sicilian Defense', 'B44', 'Magnus Carlsen', 'Fabiano Caruana', 'World Championship (rapid tiebreak)', 2018, '1-0', 5, null, 10, '["e4","c5","Nf3","e6","c4","Nc6","d4","cxd4","Nxd4","Bc5","Nc2","Nf6","Nc3","O-O","Be3","b6","Be2","Bb7","O-O","Qe7","Qd2","Rfd8","Rfd1","Ne5","Bxc5","bxc5","f4","Ng6","Qe3","d6","Rd2","a6","Rad1","Qc7","b3","h6","g3","Rd7","Bf3","Re8","Qf2","Ne7","h3","Red8","Bg2","Nc6","g4","Qa5","Na4","Qc7","e5","dxe5","Nxc5","Rxd2","Rxd2","Rxd2","Qxd2","Ba8","fxe5","Qxe5","Nd7","Qb2","Qd6","Nxd7","Qxd7","Qxc2","Qe8+","Kh7","Qxa8","Qd1+","Kh2","Qd6+","Kh1","Nd4","Qe4+","f5","gxf5","exf5","Qe3","Ne6","b4","Ng5","c5","Qf6","c6","Ne6","a4","Nc7","Qf4","Ne6","Qd6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-caruana-2020', 'Carlsen vs Caruana, Carlsen Inv Prelim', 'Queen''s Gambit Declined', 'D37', 'M. Carlsen', 'F. Caruana', 'Carlsen Inv Prelim', 2020, '1-0', 3, null, 10, '["d4","Nf6","c4","e6","Nf3","d5","Nc3","dxc4","e3","a6","a4","c5","Bxc4","Nc6","O-O","cxd4","exd4","Be7","Be3","O-O","Ne5","Bd7","Nxd7","Qxd7","d5","exd5","Nxd5","Nxd5","Qxd5","Qxd5","Bxd5","Bf6","Rfd1","Rfd8","Kf1","Rd7","Bf3","Rad8","Rxd7","Rxd7","Rc1","Rd6","b4","g5","Rc5","Nxb4","Rc8+","Rd8","Rxd8+","Bxd8","Bxb7","Kg7","Ke2","a5","Kd2","f5","Kc3","Kf6","Kc4","Bc7","h3","g4","Kb5","Ke5","hxg4","fxg4","Bb6","Kd6","Bxc7+","Kxc7","Be4","h5","Kxa5","Na2","g3","Nc3","Bc2","Ne2","Bg6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-nakamura-2025', 'Carlsen vs Nakamura, Clutch Chess: Champions', 'Sicilian Defense', 'B27', 'M. Carlsen', 'H. Nakamura', 'Clutch Chess: Champions', 2025, '1-0', 4, null, 10, '["e4","c5","Nf3","g6","d4","cxd4","Nxd4","Bg7","Nc3","Nc6","Be3","Nf6","Nxc6","bxc6","e5","Ng8","Bd4","Qc7","f4","Nh6","e6","f6","exd7+","Bxd7","Qf3","Rd8","Bc5","Be6","Bd3","O-O","O-O","Rfe8","Qe3","Bf7","Bxa7","Ng4","Qc5","f5","Bb6","Qb7","Bxd8","Rxd8","Ne2","Rd5","Qa3","Bxb2","Rab1","Rb5","Qa4","Bd4+","Qxd4","Rxb1","Nc3","Rb4","Qc5","Qb8","h3","Nf6","Qxe7","Nh5","Qe5","Qxe5","fxe5","Nf4","a4","Nxd3","cxd3","Rb3","Rc1","Ra3","Kf2","c5","Ke3","Be8","Nd5","Kf7","Rxc5","g5","a5","Bd7","g3","h5","h4","f4+","gxf4","gxh4","Rc7","Ke6","Ke4"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-aronian-2012', 'Carlsen vs Aronian, 4th London Chess Classic', 'Ruy Lopez', 'C77', 'M. Carlsen', 'L. Aronian', '4th London Chess Classic', 2012, '1-0', 4, null, 10, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","d3","b5","Bb3","Bc5","Nc3","O-O","Nd5","Nxd5","Bxd5","Rb8","O-O","Ne7","Nxe5","Nxd5","exd5","Re8","d4","Bf8","b3","Bb7","c4","d6","Nf3","Qf6","Be3","Bc8","Qd2","Qg6","Kh1","h6","Rac1","Be7","Ng1","Bg5","Bxg5","Qxg5","Rfd1","bxc4","bxc4","Qxd2","Rxd2","a5","h3","Rb4","Nf3","Bf5","c5","Kf8","Nh2","Reb8","Ng4","Rb1","Rxb1","Rxb1+","Kh2","a4","Ne3","Bg6","Kg3","Rb4","Kf3","Ke7","Ke2","Kd7","f3","Rb5","Nd1","Rb4","c6+","Kc8","Nc3","f6","Ke3","Rc4","Ne2","a3","h4","Rb4","g4","Rb1","h5","Bh7","f4","f5","g5","Rh1","Ng3","Rh3","Kf3","hxg5","fxg5","g6","Re2","Kd8","hxg6","Bxg6","Re6","Bf7","g6","Bg8","g7","f4","Kxf4","Rh2","Nf5","Rxa2","Rf6","Re2","Rf8+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-so-2017', 'Carlsen vs So, chess.com Speed 1m+1spm 2017', 'Réti Opening', 'A05', 'M. Carlsen', 'W. So', 'chess.com Speed 1m+1spm 2017', 2017, '1-0', 3, null, 10, '["Nf3","Nf6","g3","b6","Bg2","Bb7","O-O","c5","d3","g6","e4","Bg7","a4","O-O","Re1","Nc6","Nbd2","d6","Nc4","a6","e5","Nxe5","Nfxe5","Bxg2","Kxg2","dxe5","Nxe5","e6","Qf3","Nd5","Bd2","Qc7","Nc4","b5","axb5","axb5","Rxa8","Rxa8","Ne3","Rd8","Nxd5","Rxd5","Qxd5"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-ding-liren-2022', 'Carlsen vs Ding Liren, Charity Cup KO 2022', 'Indian Game', 'E10', 'M. Carlsen', 'Ding Liren', 'Charity Cup KO 2022', 2022, '1-0', 4, null, 10, '["d4","Nf6","c4","e6","Nf3","d5","g3","Bb4+","Bd2","Be7","Bg2","O-O","Qc2","c6","Bf4","Nbd7","h4","b6","Nc3","Ba6","cxd5","cxd5","O-O","b5","a3","Rc8","Rfc1","Bb7","Qb3","a6","Na2","Rc4","e3","h6","Nd2","Rxc1+","Rxc1","Qa8","Bc7","Rc8","Ba5","Ne8","Qd1","Nd6","Rxc8+","Qxc8","Bb4","Nb6","Nc1","Nbc4","Nd3","a5","Bc5","a4","Nxc4","dxc4","Nb4","Bxg2","Kxg2","Nf5","e4","Qb7","Kf3","e5","Nd5","Bxc5","dxc5","Nd4+","Kg2","Kf8","f4","Qc6","Qh5","f5","fxe5","fxe4","e6","Qxe6","Nf4","Qf5","Qd1","g5","hxg5","hxg5","Qxd4","gxf4","c6","fxg3","c7","Kf7","Qa7","Kg6","Qe3","Kf7","Qxg3","Qe6","Qh3","Qg6+","Kh1","Qf6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-mamedyarov-2019', 'Carlsen vs Mamedyarov, 81st Tata Steel GpA', 'Queen''s Gambit Accepted', 'D27', 'M. Carlsen', 'S. Mamedyarov', '81st Tata Steel GpA', 2019, '1-0', 4, null, 10, '["Nf3","d5","d4","Nf6","c4","dxc4","e3","e6","Bxc4","c5","O-O","a6","b3","b6","dxc5","Qxd1","Rxd1","Bxc5","Bb2","Nbd7","Nbd2","Bb7","Be2","O-O","Nc4","Rfd8","Ne1","Bd5","Rac1","Rac8","Nd3","Be7","Nce5","Bb7","Nc4","Bd5","Nd2","Bb7","Kf1","h6","Bf3","Nd5","Nc4","b5","Na5","Ba8","a3","g5","h3","f5","b4","Kf7","Nb3","Bf6","Bxf6","Kxf6","Nbc5","N5b6","Be2","Nc4","a4","Ndb6","a5","Nd5","Nxa6","Ndxe3+","fxe3","Nxe3+","Kg1","Nxd1","Rxd1","Rc2","Bf3","Be4","Nac5","Bxd3","Rxd3","Rxd3","Nxd3","e5","Bb7","e4","Nc5","Ke5","a6","Ra2","Bc6","h5","Bxb5","g4","hxg4","hxg4","Bc4","Ra1+","Kh2","f4","b5","f3","b6","Kf4","Nxe4"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-kramnik-2016', 'Carlsen vs Kramnik, GCT Rapid Paris 2016', 'Queen''s Gambit Declined', 'D35', 'M. Carlsen', 'V. Kramnik', 'GCT Rapid Paris 2016', 2016, '1-0', 5, null, 10, '["d4","d5","c4","e6","Nc3","Nf6","cxd5","Nxd5","e4","Nxc3","bxc3","c5","Nf3","cxd4","cxd4","Bb4+","Bd2","Bxd2+","Qxd2","O-O","Bc4","Nd7","O-O","b6","a4","Bb7","Bd3","e5","Qe3","exd4","Nxd4","Nc5","Bc2","Re8","f3","Qf6","a5","Rad8","Rfd1","Ba6","axb6","axb6","Ba4","Nxa4","Rxa4","b5","Rb4","Rd7","Rc1","Red8","e5","Qb6","Rc6","Qa7","Nf5","Qxe3+","Nxe3","Ra8","Kf2","g6","h4","h5","e6","fxe6","Rxe6","Kh7","Rf4","Bc8","Rb6","Ra2+","Kg3","Re2","Re4","Bb7","Nd5","Rxe4","Nf6+","Kg7","Nxd7","Re7","Nb8","Rc7","Rxb5","Kf6","Rb2","Kf5","Rb6","Re7","Rb5+","Kf6","Kf4","Rc7","Rb6+","Kg7","Rd6","Rc4+","Kg3","Rc7","Rd7+","Rxd7","Nxd7","Ba6","Nc5","Bf1","Ne4","Kf7","Nd2","Bd3","Kf4","Ke6","Kg5","Kf7","Nb3","Bf1","g3","Kg7","Nd4","Bc4","f4","Bd3","f5","gxf5","Nxf5+","Kh7","Ne3"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-firouzja-2021', 'Carlsen vs Firouzja, World Rapid 2021', 'Caro-Kann Defense', 'B12', 'M. Carlsen', 'A. Firouzja', 'World Rapid 2021', 2021, '1-0', 4, null, 10, '["e4","c6","d4","d5","e5","Bf5","c4","e6","Nc3","Ne7","h3","Nd7","Nf3","Bg6","b3","Nf5","Be2","Bb4","Bb2","O-O","O-O","f6","a3","Ba5","cxd5","cxd5","exf6","Qxf6","Rc1","Nh4","Nxh4","Qxh4","b4","Bd8","Bg4","Bf5","Bxf5","Rxf5","Qe2","Nf8","Nd1","Bb6","Ne3","Rg5","f4","Rg3","Kh2","Rg6","Ng4","Qd8","a4","Bc7","b5","Bd6","Rc3","Rc8","Rxc8","Qxc8","Ne5","Rf6","Rc1","Qd8","g3","Rf5","Qd3","g5","Ng4","Kg7","Ne3","Rf7","f5","Qd7","Rf1","h6","Kg2","Kg8","Ng4","Kg7","f6+","Kh8","Nxh6","Rh7","Ng4","Qe8","Ba3","Bxa3","Qxa3","Qc8","Rc1","Qe8","Ne5","Kg8","Qf3","Qd8","Rf1","Kh8","Qe3","Qc8","Rf2","g4","h4","Rh5","Nf7+","Kg8","Ng5"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-topalov-2010', 'Carlsen vs Topalov, 3rd Pearl Spring', 'Ruy Lopez', 'C84', 'M. Carlsen', 'V. Topalov', '3rd Pearl Spring', 2010, '1-0', 3, null, 10, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","d3","b5","Bb3","d6","a4","Rb8","axb5","axb5","Nbd2","O-O","Re1","Bd7","c3","Ra8","Rxa8","Qxa8","d4","h6","Nf1","Re8","Ng3","Qc8","Nh4","Bf8","Ng6","Na5","Nxf8","Rxf8","Bc2","Re8","f4","Bg4","Qd3","exf4","Bxf4","Nc4","Bc1","c5","Rf1","cxd4","cxd4","Qd8","h3","Be6","b3","Qa5","Kh2","Nh7","e5","g6","d5","Nxe5","dxe6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-erigaisi-2025', 'Carlsen vs Erigaisi, Chessable Masters Winners', 'Ruy Lopez', 'C77', 'M. Carlsen', 'A. Erigaisi', 'Chessable Masters Winners', 2025, '1-0', 5, null, 10, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","d3","b5","Bb3","Bc5","a4","Rb8","axb5","axb5","O-O","d6","Be3","O-O","h3","Bxe3","fxe3","Be6","Bxe6","fxe6","Nbd2","d5","c3","b4","Ra6","bxc3","bxc3","Rb6","Rxb6","cxb6","Qb3","Qd6","exd5","exd5","Ne4","Qd8","Rb1","Na5","Nxf6+","Rxf6","Qa2","Nc6","e4","Ne7","Nxe5","Qc7","Ng4","Rd6","Rc1","Rd8","d4","Qf4","Re1","h5","Ne5","Qg3","Qf2","Qxf2+","Kxf2","dxe4","Rxe4","b5","Re1","Nd5","Rc1","Rc8","c4","bxc4","Rxc4","Rxc4","Nxc4","Kf7","Kf3","g5","Ne3","Nf6","Ke2","Ke6","Kd3","h4","Kc4","Kd6","d5","Nh5","Kd4","Ng3","Nc4+","Kd7","Ke5","Nh5","Kf5","Nf4","Ne3","Kd6","Kxg5","Ke5","Ng4+","Ke4","d6","Ne6+","Kxh4","Kd5","d7","Kd6","Nf6","Ke7","Ne4","Kxd7","Kg4","Ke7","h4","Nd4","Kg5","Kf7","h5","Kg7","g4","Ne6+","Kh4","Nd4","g5","Nf3+","Kg4","Nd4","Nd6","Nc6","Nf5+","Kf7","Kf4","Nb4","Ne3","Nd3+","Kf5","Nc5","g6+","Kg7","Ng4","Nd7","h6+","Kh8","Nf6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-caruana-2020-b', 'Caruana vs Carlsen, Carlsen Inv Prelim', 'Alekhine Defense', 'B03', 'F. Caruana', 'M. Carlsen', 'Carlsen Inv Prelim', 2020, '0-1', 3, null, 10, '["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","f4","g6","Nc3","Bg7","Be3","Be6","Nf3","O-O","b3","dxe5","dxe5","Nc6","Ne4","f6","Nc5","Qc8","exf6","Bxf6","Be2","Rd8","Qc1","Bf5","O-O","Nd7","Nd3","Bxa1","Qxa1","Nf6","Nde5","Nxe5","Nxe5","Qe6","Bd4","Nd7","h3","Nxe5","Bxe5","c6","Qc3","h5","Re1","Kf7","Qg3","Rd2","Bf3","Rd3","Qg5","Rad8","Kf2","Rd2+","Kg3","R8d3","Qh6","Bxh3","Kh4","Rxg2"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-so-2017-b', 'So vs Carlsen, PRO League KO Stage 2017', 'Bogo-Indian Defense', 'E11', 'W. So', 'M. Carlsen', 'PRO League KO Stage 2017', 2017, '0-1', 3, null, 10, '["d4","Nf6","c4","e6","Nf3","Bb4+","Bd2","a5","a3","Bxd2+","Qxd2","b6","Nc3","Bb7","g3","O-O","Bg2","Ne4","Nxe4","Bxe4","O-O","a4","Qe3","Bb7","Qd3","f5","Ne5","Bxg2","Kxg2","d6","Nf3","Qf6","e4","Nc6","Rae1","Ra5","d5","fxe4","Qxe4","exd5","cxd5","Ne7","Rd1","Qf5","Qxe7","Qxf3+","Kg1","Rc5","Rd2","h6","Re1","Rf5","Re3","Rc1+","Re1","Rxe1+","Qxe1","Re5","Qc1","b5","h3","Kf8","h4","Ke8","Kh2","Kd8","Qh1","Qb3","Qg2","Re1","Qh3","Qf3","Qg2","Qf5","Qh3","Rh1+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-anand-2011', 'Anand vs Carlsen, 20th Amber Rapid', 'Ruy Lopez', 'C77', 'V. Anand', 'M. Carlsen', '20th Amber Rapid', 2011, '0-1', 4, null, 10, '["e4","e5","Nf3","Nc6","Bb5","Nf6","Qe2","a6","Ba4","Be7","c3","d6","O-O","O-O","d4","Bd7","d5","Nb8","Bxd7","Nbxd7","c4","g6","Nc3","Nh5","Rb1","Ng7","b4","f5","Be3","Rb8","Rfd1","Qe8","a4","f4","Bd2","g5","h3","h5","Nh2","Qg6","f3","Ne8","Rdc1","Nef6","Kf1","Kf7","Ke1","g4","Kd1","gxh3","gxh3","Rg8","Kc2","Qg2","Rh1","Qxe2","Nxe2","Rg2","Kd3","Nb6","Rbg1","Rbg8","Rxg2","Rxg2","a5","Nxc4","Bc1","b5","axb6","Nxb6","Nf1","Nh7","h4","Nf8","Bd2","Ng6","Be1","Na4","Rg1","Rxg1","Nxg1","Bxh4","Bd2","Ke7","Nh3","Kd7"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-mamedyarov-2018', 'Mamedyarov vs Carlsen, World Blitz 2018', 'Queen''s Gambit Declined', 'D30', 'S. Mamedyarov', 'M. Carlsen', 'World Blitz 2018', 2018, '0-1', 4, null, 10, '["d4","d5","c4","e6","Nf3","a6","e3","Nf6","Nc3","dxc4","Bxc4","b5","Be2","Bb7","O-O","Nbd7","b3","c5","Bb2","Be7","Rc1","O-O","Qc2","Rc8","Qb1","Qb6","Rfd1","Rfd8","h3","h6","dxc5","Nxc5","Rxd8+","Rxd8","Rd1","b4","Rxd8+","Qxd8","Na4","Nxa4","bxa4","Qd5","Bxf6","gxf6","Qb3","a5","Qc2","Qc6","Qxc6","Bxc6","Bd1","f5","Nd4","Bd5","Bb3","Bb7","Bc4","Bc5","Kf1","Bxd4","exd4","Bc6","Bb3","f4","g3","fxg3","fxg3","Kf8","Kf2","Ke7","g4","f6","Ke3","Kd6","Kf4","Bd5","h4","Bxb3","axb3","Kd5","Ke3","e5","dxe5","Kxe5","Kf3","Kd4","Kf4","Kc3","Kf5","Kxb3","Kxf6","Kxa4","g5","hxg5","hxg5","b3","g6","b2","g7","b1=Q","g8=Q","Qb2+","Kf5","Qd4","Qa2+","Kb4","Qb1+","Kc5","Qc2+","Kd6","Qe4","Kc5","Qc2+","Qc4","Qf2+","Kc6","Ke5","Qc5+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-aronian-2013', 'Aronian vs Carlsen, Norway Supreme Masters Blitz 2013', 'Indian Game', 'A46', 'L. Aronian', 'M. Carlsen', 'Norway Supreme Masters Blitz 2013', 2013, '0-1', 3, null, 10, '["d4","Nf6","Nf3","e6","e3","g6","Bd3","c5","O-O","Bg7","Nbd2","O-O","dxc5","Qc7","Nb3","b6","cxb6","axb6","Bd2","Bb7","h3","e5","Be2","d5","a4","Nbd7","a5","Rfc8","a6","Bc6","Bb4","Bf8","Bxf8","Nxf8","Ne1","Rd8","c3","Ne6","Nc2","Rac8","f4","d4","fxe5","dxc3","Ncd4","cxb2","exf6","bxa1=Q","Qxa1","Qe5","Nf5","Qe4","Nh6+","Kf8","Qa3+","Nc5","Rf3","Qb1+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-nakamura-2025-b', 'Nakamura vs Carlsen, Clutch Chess: Champions', 'Pirc Defense', 'B07', 'H. Nakamura', 'M. Carlsen', 'Clutch Chess: Champions', 2025, '0-1', 4, null, 10, '["e4","d6","d4","Nf6","Nc3","e5","Nge2","c6","a4","Be7","g3","a5","Bg2","Na6","O-O","O-O","h3","h5","f4","Nb4","Be3","Qc7","Nb1","exd4","Nxd4","Re8","c3","Na6","Nd2","Bf8","Bf2","Nc5","Qc2","Bd7","b4","axb4","cxb4","Na6","Rab1","Rac8","N4f3","c5","bxc5","Nxc5","e5","Bxa4","Qa2","dxe5","Nxe5","Bc6","Nxc6","bxc6","Qc4","Nb7","Rfc1","Nd6","Qa4","Re2","Bb6","Qd7","Nf1","c5","Qxd7","Nxd7","Ba5","c4","Bb4","Nc5","Bf3","Ree8","Bc3","Nd3","Rc2","h4","gxh4","Nxf4","h5","Nxh3+","Kh1","Ne4","Be1","Nhg5","Bg4","Rc5","Ne3","Nf6","Bf2","Nge4","Bg1","Nxg4","Nxg4","Rxh5+","Nh2","c3","Rd1","Ng3+","Kg2","Re2+","Rxe2","Nxe2","Be3","c2","Ra1","Bd6","Nf3","Bf4","Ra8+","Kh7","Rc8","Bxe3"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-kramnik-2016-b', 'Kramnik vs Carlsen, GCT Blitz Paris 2016', 'Italian Game', 'C55', 'V. Kramnik', 'M. Carlsen', 'GCT Blitz Paris 2016', 2016, '0-1', 4, null, 10, '["e4","e5","Nf3","Nc6","Bc4","Nf6","d3","Be7","O-O","O-O","Re1","d6","a4","Na5","Ba2","c5","Nbd2","Nc6","c3","Be6","Bxe6","fxe6","b4","cxb4","cxb4","Nxb4","Qb3","d5","Nxe5","Rc8","Rb1","Nc2","Rf1","Nd4","Qd1","Qc7","Ndf3","dxe4","dxe4","Nxf3+","Nxf3","Nxe4","Qe2","Qc4","Qxc4","Rxc4","Rxb7","Bc5","Bb2","Nf6","Ng5","Re8","a5","h6","Nf7","Re7","Rxe7","Bxe7","Ne5","Rc2","Bd4","Bc5","Nc6","a6","Ra1","Bd6","Bxf6","Rxc6","Bd4","Bc7","g3","Kf7","Kg2","h5","Kf3","e5","Be3","Ke6","Ra4","Kd5","g4","g6","gxh5","gxh5","Rh4","Rf6+","Ke2","Rf5","Bb6","Bd6","f3","Be7","Ra4","Rg5","Kf1","Rg6","Ra2","Rc6","Rd2+","Ke6","Kg2","Rc3","Re2","Kf5","Re4","Rc2+","Kh3","Bg5","Be3","Rc3"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-ding-liren-2019', 'Ding Liren vs Carlsen, Croatia GCT 2019', 'Catalan Opening', 'E06', 'Ding Liren', 'M. Carlsen', 'Croatia GCT 2019', 2019, '0-1', 4, null, 10, '["d4","Nf6","c4","e6","Nf3","d5","g3","Be7","Bg2","O-O","O-O","dxc4","Qc2","b5","a4","b4","Nfd2","Nd5","Nxc4","c5","dxc5","Ba6","Ne3","Nd7","Nxd5","exd5","c6","Rc8","Bf4","Nc5","c7","Qd7","Nd2","g5","Be5","f6","Bd4","Rxc7","Qd1","Ne6","Nb3","Bc4","Na5","Nxd4","Qxd4","Kg7","Rfc1","Bxe2","Rxc7","Qxc7","Re1","Bc5","Qxd5","Re8","Qb7","Qxb7","Nxb7","Bf8","Bc6","Re7","f3","Bc4","Rxe7+","Bxe7","Kf2","f5","Ke3","Bg8","Kd3","g4","Na5","Bc5","Nc4","Bg1","Ne3","Be6","fxg4","fxg4","Ke2","h5","Bd5","Bd7","Bb3","Bxh2","Kf2","h4","gxh4","Be5","Nc4","g3+","Kg1","Bf4","Bd1","Bc6","b3","Kh6","a5","Be4","Kf1","Kg7","Kg1","Kf6","Kf1","Ke6","h5","Kd5","a6","Kd4","Bg4","Kc3","Be6","Bc2","Na5","Bc7","Nb7","Bd3+","Kg1","Bxa6"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-vachier-lagrave-2016', 'Vachier Lagrave vs Carlsen, World Blitz 2016', 'Ruy Lopez', 'C78', 'M. Vachier-Lagrave', 'M. Carlsen', 'World Blitz 2016', 2016, '0-1', 4, null, 10, '["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","b5","Bb3","Bb7","d3","Be7","Nc3","O-O","a3","d6","Nd5","Nxd5","Bxd5","Qd7","d4","exd4","Nxd4","Bf6","Nf5","Nd8","Re1","Re8","c3","Bxd5","Qxd5","Nc6","Ng3","g6","Bf4","Ne5","Rad1","Rad8","Re2","c6","Qa2","Qg4","Bc1","h5","h3","Qe6","Qxe6","Rxe6","f4","Nc4","b3","Na5","b4","Nc4","Rd3","Rde8","e5","dxe5","f5","e4","Rd7","gxf5","Nxf5","e3","Rd3","Re5","Nd4","Rd5","Bxe3","Rde5","Nc2","Bg5","Kf2","Rf5+","Kg1","Rfe5","Kf2","f5","Re1","Nxe3","Nxe3","f4","Nc2","Bh4+"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

insert into engine_games (id, title, opening, eco, white, black, event, year, result, difficulty, start_fen, max_start_move, moves, is_generated, source)
values ('carlsen-topalov-2010-b', 'Topalov vs Carlsen, 3rd Pearl Spring', 'Catalan Opening', 'E00', 'V. Topalov', 'M. Carlsen', '3rd Pearl Spring', 2010, '0-1', 3, null, 10, '["d4","Nf6","c4","e6","g3","Bb4+","Bd2","Bxd2+","Qxd2","d5","Bg2","c6","Nf3","Nbd7","O-O","b6","Rc1","O-O","b4","Bb7","Qb2","Rb8","Nbd2","Qe7","e3","Rfc8","Rc2","c5","bxc5","bxc5","Qa3","Rc6","Rac1","Ra6","Qd3","h6","Qe2","dxc4","Qxc4","cxd4","Nxd4","Rb6","Bxb7","R8xb7","Kg2","Ne5","Qc5","Qxc5","Rxc5","Rb2","R1c2","Nd3","Rc8+","Kh7","N4f3","a5","h3","a4","a3","g5","Rxb2","Rxb2","Rc3","Nxf2","Rc7","N2e4"]'::jsonb, false, 'curated')
on conflict (id) do update set title=excluded.title, opening=excluded.opening, eco=excluded.eco, white=excluded.white, black=excluded.black, event=excluded.event, year=excluded.year, result=excluded.result, difficulty=excluded.difficulty, start_fen=excluded.start_fen, max_start_move=excluded.max_start_move, moves=excluded.moves;

